Rewrite should now be at feature parity with master branch. Still have a few cases to test.

diff --git a/funcs/etc b/funcs/etc
--- a/funcs/etc
+++ b/funcs/etc
@@ -2,7 +2,7 @@
 # Utility functions.
 
 # Print to stdout if env vars are enabled.
-debug_print () { if [[ "${ARCADIA_DEBUG:-}" ]]; then echo "DEBUG: $*"; fi }
+debug_print () { if [[ "${ARCADIA_DEBUG:-}" ]]; then echo "DEBUG: $*" >&2; fi; }
 
 die () { echo "FATAL: $*"; exit 1; }
 assert () { test "$@" || die "Assertion $* failed"; }
@@ -10,12 +10,14 @@ assert () { test "$@" || die "Assertion $* failed"; }
 is () { local a="${1:-}"; [[ "${a,,}" =~ yes|on|true|^[0-9]*[1-9][0-9]*$ ]]; }
 # Shushes a command. All output directed to /dev/null.
 shh () { "$@" >/dev/null 2>&1; }
-# Checks to see if a function is set and if so, runs it.
+
+# Checks to see if a user function is set and if so, runs it.
 fn () {
+    set +eu +o pipefail
     if [[ "$(type -t "${1:-}")" = "function" ]]; then
         debug_print "Running ${1:-}"
         "$@"
-    else return 1; fi
+    fi; set -eu -o pipefail; return 0
 }
 
 # Sources specified files if they exist. Returns 1 if any are missing.
@@ -28,19 +30,36 @@ include () {
     return $code
 }
 
+# Run a given arcadia module.
+module () {
+    local module="${1:-}"; shift; [[ "$module" ]] || exit
+    local modules_dir; for modules_dir in "$arcadia_path" \
+     "${XDG_DATA_HOME:-$HOME/.local/share}/arcadia"; do
+     if [[ -e "$modules_dir/modules/$module" ]]; then
+        mod_file=$(readlink -f "$modules_dir/modules/$module")
+        if file "$mod_file" | grep -q "Bourne-Again shell script"; then
+            # If it's a bash script, we source it to run it in the current
+            # context so that nothing needs to be exported.
+            . "$mod_file"; else exec "$mod_file" "$@"
+        fi
+        return 0
+    fi; done
+    die "Module $module not found."
+}
+
 # Find a binary and optionally execute it with args.
 declare -A bins; declare -A aliases
 bin () {
     local bin=${1:?}; shift
-    if [[ ! -x "${bins[$bin]}" ]]; then
+    if [[ ! -x "${bins[$bin]:-}" ]]; then
         debug_print "Searching for program: $bin"
-        for alias in $bin ${aliases[$bin]}; do
+        for alias in $bin ${aliases[$bin]:-}; do
             bins[$bin]="$(which "$alias")"
-            [[ -x "${bins[$bin]}" ]] && break
+            [[ -x "${bins[$bin]:-}" ]] && break
         done
     fi
-    [[ ! -x "${bins[$bin]}" ]] && return 1
-    [[ $# -gt 0 ]] && "${bins[$bin]}" "$@"
+    [[ ! -x "${bins[$bin]:-}" ]] && return 1
+    [[ $# -gt 0 ]] && "${bins[$bin]:-}" "$@"
     return 0  # We don't want to return the program's error code.
 }
 
@@ -120,14 +139,14 @@ check_power () {
     if [[ ! "$power" || "$power" -eq 1 ]]; then
         debug_print "Computer is on AC"
         while [[ $# -ge 2 ]]; do
-            export ${1:?}="${2:?}"
+            declare ${1:?}="${2:?}"
             shift 3
         done
         return 0
     else
         debug_print "Computer is on battery"
         while [[ $# -ge 3 ]]; do
-            export ${1:?}="${3:?}"
+            declare ${1:?}="${3:?}"
             shift 3
         done
         return 1
diff --git a/funcs/meta b/funcs/meta
--- a/funcs/meta
+++ b/funcs/meta
@@ -4,6 +4,17 @@
 # This function gets redefined when it's time to actually load the game.
 select_file () { true; }
 
+# Loads up the metas for a given game.
+load_game () {
+    game="${1:?}"
+    find_game "$game"
+    check_platform! "$(dirname "$game")"
+    load_platform "$(dirname "$game")"
+    load_game_file "$game" || die "Failed to load $game."
+    set_runner "${platform:-}"
+    if [[ ! "${steam_id:-}" ]]; then find_file; fi
+}
+
 # Finds a game if given only a name.
 find_game () {
     game="$(readlink -f "$1")"
@@ -52,7 +63,7 @@ load_platform () {
     debug_print "Loading platform meta for $platform_dir"
     platform_base="$(basename "$platform_dir")"  # shellcheck disable=SC2034
     get_exts "${platform:-}"
-    include "$platform_dir/arcadia-platform.meta"
+    include "$platform_dir/arcadia-platform.meta" || true
 }
 
 # Get a list of extensions that are associated with the platform to assist
@@ -101,7 +112,7 @@ is_game () {
 }
 
 # Infer information about the game and load metas if present.
-load_game () {
+load_game_file () {
     local game; game=$(readlink -f "${1:-}")
     is_game "$game" || { debug_print "$game is not a game"; return 1; }
     debug_print "Loading game meta for ${1:-}"
@@ -129,7 +140,7 @@ load_game () {
 declare -A img
 find_image () {
     local type="$1"
-    [[ -e "${img[$type]}" ]] && return 0
+    [[ -e "${img[$type]:-}" ]] && return 0
     for e in png jpg gif ico bmp; do
         for n in "$type.$e" ".$type.$e" \
          "arcadia-$type.$e" ".arcadia-$type.$e"; do
